site_name: "mu-pipelines Docs"
site_url: "https://mosaicsoft-data.github.io/mu-pipelines-doc/"
theme:
  name: "material"
  custom_dir: docs\overrides
  title: "mu-pipelines home page"
  description: "You can find all documents and videos on how to use mu-pipelines by mosaicsoft"
  tags:
    - lakehouse
    - ETL
    - data pipelines
    - open source ETL
    - data mesh
extra:
  google_site_verification: '-H19MiKa-4NI9aJHAM1bxBBebrS7IrubqX-_lylLcqw'
  search:
    indexing: 'full'
plugins:
    - mkdocs-video:
        is_video: True
        video_muted: True
        video_controls: True
        css_style:
        width: "50%"
    - mkdocstrings
    - ultralytics:
        verbose: True
        enabled: True
        default_image: "https://example.com/default-image.png"
        default_author: "mupipelines@gmail.com"
        add_desc: True
        add_image: True
        add_keywords: True
        add_share_buttons: True
        add_authors: False
        add_json_ld: False
        add_css: True
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Ingestion Commands: 
      CSV: ingest-command\ingestCSV.md
      Kafka: ingest-command\ingestKafka.md
      Databases (JDBC): ingest-command\ingestJDBC.md
      Rest API: ingest-command\ingestRestAPI.md
  - Transform Commands: 
      SQL Transformation: transform-command\transformSQL.md
  - Destination Commands: 
      CSV: destination-command\destinationCSV.md
      Parquet: destination-command\destinationParquet.md
      Deafult Catalog (Data Lake/Lakehouse): destination-command\destinationDefaultCatalog.md
  - Streaming Commands: 
      Kafka to Iceberg Configuration: streaming-command\stream-kafka-iceberg.md
  - Connection Properties: connection_properties.md
  - Global Properties: global_properties.md
  - Secrets Properties: secrets_properties.md
  - Developer Docs: 
      CI-CD: Developer Docs\CI-CD.md
      How to create data mesh: Developer Docs\How to create data mesh.md
  - Demo Videos: 
      Introduction: Demo Videos\Introduction.md
      Use in databricks: Demo Videos\Use in databricks.md
  - FAQ: faq.md

repo_url: "https://mosaicsoft-data.github.io/mu-pipelines-doc/"
